# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20171230_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=255, verbose_name='\u6982\u8ff0'),
        ),
    ]
