# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20171230_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='/static/uploads'),
        ),
    ]
