# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20171231_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
    ]
